## 📝 Description
Provide a clear and concise description of your changes and the related issue.

*Issue ID:* #ISSUE_ID

---

### 🔍 Changes Made
- [ ] Updated dependencies  
- [ ] Added/modified scripts  
- [ ] UI changes  
- [ ] API changes  
- [ ] Database changes  
- [ ] Other (specify below)

---

### 🖼 Screenshots / UI Updates
Attach before/after screenshots or write N/A.

---

### ✅ Checklist
- [ ] My code follows the project's coding standards  
- [ ] Linked the correct issue ID  
- [ ] Added necessary documentation (if applicable)  
- [ ] Tested changes locally  
- [ ] Updated/added relevant tests  
- [ ] No new warnings/errors introduced  

---

### 🚀 Additional Notes
Add any extra context, details, or reviewer notes here.
